apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc-external-secret
  namespace: monitoring
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-client-secret
    creationPolicy: Owner
  data:
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: kv/oidc_client_secret
        property: secret
    - secretKey: PROJECT001_PASSWORD
      remoteRef:
        key: kv/oidc_client_secret
        property: project001_password
