apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-grafana-realm
  namespace: keycloak
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-grafana-realm
    creationPolicy: Owner
  data:
    - secretKey: grafana-realm.json
      remoteRef:
        key: kv/grafana-realm
        property: grafana-realm