apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-datasource-secret
  namespace: monitoring
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-datasource-secret
    creationPolicy: Owner
  data:
    - secretKey: PROJECT001_PASSWORD
      remoteRef:
        key: kv/loki-datasource-password
        property: project001_password
