apiVersion: v1
kind: Secret
metadata:
  name: vault-root-key
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
data:
  token: aHZzLllvQkVDeDdMcTVmODJDQ0s3V2V3TUxoNw==
{{/* ! MAKE SURE TO USE 'echo -n root-key | base64 '*/}}