apiVersion: v1
kind: Service
metadata:
  name: grafana-node-port
spec:
  type: NodePort
  ports:
    - port: 30000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
