apiVersion: v1
kind: Service
metadata:
  name: keycloak-node-port
  namespace: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      nodePort: 30088
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak