apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgre-password-external
  namespace: keycloak
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-postgre-pw
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/keycloak-postgre-pw
        property: password