apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-password-external
  namespace: keycloak
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-pw
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/secret
        property: key