apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki-basic-auth
  namespace: monitoring
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: loki-basic-auth
    creationPolicy: Owner
  data:
    - secretKey: .htpasswd
      remoteRef:
        key: kv/nginx-basic-auth
        property: .htpasswd

