apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-loki-config
  namespace: monitoring
data:
  default.conf: |
    map $remote_user $org_id {
        default "";
        project001 "project001";
        admin "admin";
    }

    server {
      listen 80;

      location / {
        auth_basic "Loki Auth";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;

        proxy_set_header X-Scope-OrgID $org_id;
        proxy_pass http://loki:3100;
      }
    }