apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-loki-config
  namespace: monitoring
data:
  default.conf: |
    server {
      listen 80;

      location / {
        auth_basic "Loki Auth";
        auth_basic_user_file /etc/nginx/auth/.htpasswd;

        set $org_id "";

        if ($remote_user = "project001") {
            set $org_id "project001";
        }

        if ($remote_user = "admin") {
            set $org_id "project002";
        }

        proxy_set_header X-Scope-OrgID $org_id;
        proxy_pass http://loki.monitoring.svc.cluster.local:3100
    }