apiVersion: v1
kind: ConfigMap
metadata:
  name: occurrance-traker
data:
  application.yaml: |
    spring:
      application:
        name: OccurenceTrakerApplication
      data:
        redis:
          host: redis-master.project-001.svc.cluster.local
          port: 6379
          usePassword: true
          password: ${REDIS_PASSWORD}
    logging:
      pattern:
        console: ts=%d{yyyy-MM-dd'T'HH:mm:ss.SSS} level=%level thread="%t" traceId=%X{traceId} spanId=%X{spanId} %replace(%replace(%X{trackingKey}){'"', '\''}){'([^=]+)=\'?([^,]+)\'?,?', '$1="$2" '} caller=%c{1} msg="%replace(%msg){'"', '\''} %replace(%xEx){'"', '\''}"%n

    management:
      prometheus:
        metrics:
          export:
            enabled: true

      endpoints:
        web:
          exposure:
            include: health, info, prometheus