apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: redis-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: kv/redis-password
        property: password