apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-password
spec:
  refreshInterval: "1500s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secrets.redis.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.redis.key }}
      remoteRef:
        key: kv/{{ .Values.secrets.redis.name }}
        property: {{ .Values.secrets.redis.key }}