apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: secure-access
  namespace: monitoring
spec:
  chain:
    middlewares:
      - name: ip-allowlist
      - name: rate-limit
      - name: redirect-scheme
      - name: inflight-limit