apiVersion: v1
kind: Service
metadata:
  name: argocd-node-port
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 30080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: argocd-server
