apiVersion: v1
kind: Service
metadata:
  name: vault-node-port
  namespace: vault
spec:
  ports:
    - name: http
      nodePort: 30082
      port: 8200
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    app.kubernetes.io/part-of: vault
  type: NodePort