alloy:

  fullnameOverride: alloy

  serviceAccount:
    create: true
    name: "alloy"

  controller:
    type: 'daemonset'
    tolerations:
      - effect: NoSchedule
        operator: Exists

    volumes:
      extra:
        - name: tmp
          hostPath:
            path: /tmp
#        - name: varlog
#          hostPath:
#            path: /var/log

  image:
    tag: v1.5.1
    digest: sha256:01a63f4e032ce54ee94b22049bc27f597e74f85566478c377f4b5c7f020c1eb3

  alloy:
    enableReporting: false

    mounts:
      varlog: true
      dockercontainers: true

      extra:
        - name: tmp
          mountPath: /tmp
#        - name: varlog
#          mountPath: /var/log

    clustering:
      enabled: false

    uiPathPrefix: /alloy/

    configMap:
      create: false
      name: alloy-config
      key: config.alloy

  configReloader:

    image:
      tag: v0.14.0
      digest: a35b35f5bd5c5dc59d6885a60ac325235d873defbc819cd1e16f52f897752c85