apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: base
      targetRevision: 1.24.2
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.24.2
      helm:
        values: |
          service:
            type: ClusterIP

          extraContainerArgs:
            - --tlsCertFile=/etc/cert-manager/tls/tls.crt
            - --tlsKeyFile=/etc/cert-manager/tls/tls.key
            - --caCertFile=/etc/cert-manager/ca/root-cert.pem
        
          env:
            ENABLE_CA_SERVER: false
            CA_ADDR: cert-manager-istio-csr.cert-manager.svc:443
        
          volumeMounts:
            - mountPath: /etc/cert-manager/tls
              name: cert-manager
              readOnly: true
            - mountPath: /etc/cert-manager/ca
              name: istio-csr-ca-configmap
              readOnly: true
        
          volumes:
            - name: cert-manager
              secret:
                defaultMode: 420
                secretName: istiod-tls
            - configMap:
                defaultMode: 420
                name: istio-ca-root-cert
                optional: true
              name: ca-root-cert
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks/0/failurePolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/0/failurePolicy

