apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 24.6.1
      helm:
        values: |
         resources:
           requests:
             cpu: 1
             memory: 512Mi
           limits:
             cpu: 10
             memory: 2048Mi
          production: true
          proxy: edge
          auth:
            adminUser: admin
            existingSecret: keycloak-admin-pw
            passwordSecretKey: password
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: keycloak.127.0.0.1.sslip.io
            pathType: Prefix
            extraTls:
              - hosts:
                - keycloak.127.0.0.1.sslip.io
                secretName: keycloak-tls
            annotations:
              cert-manager.io/cluster-issuer: vault-issuer
              traefik.ingress.kubernetes.io/router.middlewares: monitoring-secure-access@kubernetescrd
          postgresql:
            enabled: true
            auth:
              existingSecret: keycloak-postgre-pw
              secretKeys:
                userPasswordKey: password
          extraEnvVars:
            - name: KC_HOSTNAME_URL
              value: https://keycloak.127.0.0.1.sslip.io
            - name: KC_HOSTNAME_ADMIN_URL
              value: https://keycloak.127.0.0.1.sslip.io
            - name: KEYCLOAK_EXTRA_ARGS
              value: "--import-realm"
          extraVolumeMounts:
            - name: realm-secret
              mountPath: "/opt/bitnami/keycloak/data/import"
              readOnly: true
          extraVolumes:
            - name: realm-secret
              secret:
                secretName: keycloak-grafana-realm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
