apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 24.6.1
      helm:
        values: |
          resources:
            requests:
              cpu: 1
              memory: 512Mi
            limits:
              cpu: 2
              memory: 1024Mi
          production: true
          proxy: edge
          auth:
            adminUser: admin
            existingSecret: keycloak-admin-pw
            passwordSecretKey: password
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: nginx
            hostname: keycloak.127.0.0.1.sslip.io
            pathType: Prefix
            extraTls:
              - hosts:
                - keycloak.127.0.0.1.sslip.io
                secretName: keycloak-tls
            annotations:
              cert-manager.io/cluster-issuer: vault-issuer
              nginx.ingress.kubernetes.io/ssl-redirect: "false"
              nginx.ingress.kubernetes.io/use-regex: "true"
              nginx.ingress.kubernetes.io/service-upstream: "true"
              nginx.ingress.kubernetes.io/upstream-vhost: keycloak.keycloak.svc.cluster.local
              nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.1/32"
          postgresql:
            enabled: true
            auth:
              existingSecret: keycloak-postgre-pw
              secretKeys:
                userPasswordKey: password
          extraEnvVars:
            - name: KC_HOSTNAME_URL
              value: https://keycloak.127.0.0.1.sslip.io
            - name: KC_HOSTNAME_ADMIN_URL
              value: https://keycloak.127.0.0.1.sslip.io
            - name: KEYCLOAK_EXTRA_ARGS
              value: "--import-realm"
          extraVolumeMounts:
            - name: realm-secret
              mountPath: "/opt/bitnami/keycloak/data/import"
              readOnly: true
          extraVolumes:
            - name: realm-secret
              secret:
                secretName: keycloak-grafana-realm
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
