apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 24.6.1
      helm:
        values: |
          auth:
            adminUser: admin
            existingSecret: keycloak-admin-pw
            passwordSecretKey: password
          service:
            type: ClusterIP
          ingress:
            enabled: false
          postgresql:
            enabled: true
            auth:
              existingSecret: keycloak-postgre-pw
              secretKeys:
                userPasswordKey: password
  architecture: standalone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
