apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: keycloak
      targetRevision: 24.6.1
      helm:
        values: |
          production: true
          proxy: edge
          auth:
            adminUser: admin
            existingSecret: keycloak-admin-pw
            passwordSecretKey: password
          service:
            type: ClusterIP
          ingress:
            enabled: true
            ingressClassName: traefik
            hostname: keycloak.127.0.0.1.sslip.io
            pathType: Prefix
            tls: true
            extraTls:
              - hosts:
                - keycloak.127.0.0.1.sslip.io
                secretName: keycloak.127.0.0.1.sslip.io-tls
            annotations:
              cert-manager.io/cluster-issuer: vault-issuer
          postgresql:
            enabled: true
            auth:
              existingSecret: keycloak-postgre-pw
              secretKeys:
                userPasswordKey: password
          extraEnvVars:
            - name: KC_HOSTNAME_URL
              value: https://keycloak.127.0.0.1.sslip.io
            - name: KC_HOSTNAME_ADMIN_URL
              value: https://keycloak.127.0.0.1.sslip.io
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
