apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: echo-server
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/NHristovski/cloud-security-argocd-app-of-apps
      path: testing
      targetRevision: main
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: enabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
