apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: vault
      targetRevision: 1.7.5
      helm:
        values: |
          server:
            ingress:
              enabled: true
              ingressClassName: nginx
              hostname: vault.127.0.0.1.sslip.io
              pathType: Prefix
              extraTls:
                - hosts:
                  - vault.127.0.0.1.sslip.io
                  secretName: vault-tls
              annotations:
                cert-manager.io/cluster-issuer: vault-issuer
                nginx.ingress.kubernetes.io/ssl-redirect: "false"
                nginx.ingress.kubernetes.io/use-regex: "true"
                nginx.ingress.kubernetes.io/service-upstream: "true"
                nginx.ingress.kubernetes.io/upstream-vhost: vault-server.vault.svc.cluster.local
                nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, 127.0.0.1/32"
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        istio-injection: disabled
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: vault-vault-injector
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
